#!/usr/bin/env ruby

require "keald"
require "optparse"

options = {}
OptionParser.new do |o|
  o.banner = "Usage: keald [options]"

  o.on "-V", "--version", "Print the version then quit" do
    puts "keald v#{Keal::VERSION}"
    exit 0
  end
end.parse!

k = KealDaemon.new(options)
k.run
